config/routes.rb
Rails.application.routes.draw do
  root 'studies#top'
  resources :studies, only: [:new, :create] do
    collection do
      post 'calculate'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/study.rb
class Study < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  def new
  end
  
  def calculate
    @time = params[:time].to_i
    @burned_calorie = @time * 0.0295
    @foods = Food.where('calorie <= ?', @burned_calorie)
    render 'calculate'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleNewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/studies/calculate.html.erb
<h1>結果</h1>
<p>勉強時間: <%= @time %>分</p>
<p>消費カロリー: <%= @burned_calorie.round(2) %>kcal</p>
<h2>食べていいもの</h2>
<ul>
  <% @foods.each do |food| %>
    <li><%= food.name %> (<%= food.calorie %>kcal)</li>
  <% end %>
</ul>

app/views/studies/new.html.erb
<h1>消費カロリー計算</h1>
<%= form_tag calculate_studies_path do %>
  <%= label_tag :time, '勉強時間(分)' %>
  <%= text_field_tag :time %>
  <%= submit_tag '計算' %>
<% end %>

app/views/studies/top.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>はじめるボタン</title>
</head>
<body>
  <button id="start-btn">はじめる</button>
</body>
</html>